# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('term', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('risk_level', models.PositiveSmallIntegerField()),
                ('credit_history', models.BooleanField()),
                ('wages', models.PositiveIntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
    ]
